server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          # triple slash is for Windows, use double slash for Linux
          uri: file:///${user.home}/spring-cloud-config-repo
          clone-on-start: true

  security:
    user:
      name: user
      password: Passw0rd